---
ssoName: "default"
clientId: "inventory-api"
clientSecret: "OXy66zx1pZL4HYqmsgWCVa5rgGFNS91U"
userName: "nishimura"
password: "Luas@15"
tokenServerUrl: "https://dev-sso-netcompass.tdigital-vivo.com.br/realms/netcompass/protocol/openid-connect/token"
authorizationServerUrl: "https://dev-sso-netcompass.tdigital-vivo.com.br/realms/netcompass/protocol/openid-connect/auth"
appKey: null
oam: null
authScopes:
- "read"
useRefreshToken: true
renewBeforeSecs: 30
